#!/bin/sh

dt() {
    DT=$(date '+%b %d %I:%M:%S %p')
    printf "󱑍 %s" "$DT"
}

vpn() {
    VPN=$(ip addr show | grep "ppp0" | grep "inet" | awk '{print $2}')

    if [[ $VPN != "" ]]; then
        printf "󰒃 %s" "$VPN"
    fi
}

wifi() {
    case "$(cat /sys/class/net/w*/operstate 2>/dev/null)" in
            down) wifiicon="󰖪" ;;
            up) wifiicon="$(awk '/^\s*w/ { print "󰖩", int($3 * 100 / 70) "%" }' /proc/net/wireless)" ;;
    esac

    printf "%s" "$wifiicon"
}

memory() {
    MEM=$(free -h | grep Mem | awk '{print $3}')

    printf "󰍛 %s" "$MEM"
}

while true; do
  output="$(vpn) $(memory) $(wifi) $(dt) "
    xsetroot -name "$output"
    sleep 1
done
