#!/bin/bash

if [[ $1 == 't' ]]
then
    pamixer -t
elif [[ $1 == 'i' ]] || [[ $1 == 'd' ]]
then
    pamixer --allow-boost -$1 10
fi

notify-send -t 500 -h string:x-canonical-private-synchronous:volume "Vol: $(pamixer --get-volume-human)"

if command -v dwmblocks &> /dev/null
then
  pkill -RTMIN+10 dwmblocks
fi
