brew "neovim"
brew "tmux"
brew "mkcert"
brew "composer"
brew "fzf"
brew "rg"
brew "lazygit"

tap "ddev/ddev"
brew "ddev/ddev/ddev"

cask "alacritty"
cask "google-chrome"
cask "raycast"
cask "1password"
cask "docker"
cask "openvpn-connect"
cask "font-meslo-lg-nerd-font"
cask "chatgpt"
cask "tableplus"
cask "lm-studio"
cask "firefox"
